# Generated by Django 5.0.7 on 2024-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_videomodel_alter_onlineclassesmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineClassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, verbose_name='offline_description')),
                ('start_time', models.DateField(verbose_name='offline_start_time')),
                ('price', models.IntegerField(verbose_name='offline_price')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('max_participants', models.IntegerField(verbose_name='offline_max_participants')),
            ],
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='max_participants',
            field=models.IntegerField(verbose_name='offline_max_participants'),
        ),
    ]
