# Generated by Django 5.0.7 on 2024-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_offlineclassesmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='max_participants',
            field=models.IntegerField(verbose_name='online_max_participants'),
        ),
    ]
