# Generated by Django 5.0.7 on 2024-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_onlineclassesmodel_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalusermodel',
            name='money_spent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
