# Generated by Django 5.0.7 on 2024-07-15 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_globalusermodel_money_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclassesmodel',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='offlineclassesmodel',
            name='start_time_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Час:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='Назва:'),
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Опис:'),
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Локація:'),
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='max_participants',
            field=models.IntegerField(verbose_name='Максимальна кількість учасників:'),
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='price',
            field=models.IntegerField(verbose_name='Ціна:'),
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='start_time',
            field=models.DateField(verbose_name='Дата:'),
        ),
    ]
