# Generated by Django 5.0.7 on 2024-07-15 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_onlineclassesmodel_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclassesmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='online_start_time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='start_time',
            field=models.TimeField(verbose_name='online_start_time'),
        ),
    ]
