# Generated by Django 5.0.7 on 2024-07-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_remove_offlineclassesmodel_start_time_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassRegistrationModel',
            new_name='OnlineClassRegistrationModel',
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='Назва:'),
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Опис:'),
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='price',
            field=models.IntegerField(verbose_name='Ціна:'),
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='start_date',
            field=models.DateField(verbose_name='Дата:'),
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='start_time',
            field=models.TimeField(verbose_name='Час:'),
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='zoom_link',
            field=models.CharField(default=None, max_length=255, verbose_name='Посилання:'),
        ),
        migrations.CreateModel(
            name='OfflineClassRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('user_surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('number', models.IntegerField(verbose_name='Номер (без +38)')),
                ('number_of_participants', models.IntegerField(verbose_name='Кількість учасників')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.offlineclassesmodel')),
            ],
        ),
    ]
