# Generated by Django 5.0.7 on 2024-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_rename_classregistrationmodel_onlineclassregistrationmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclassesmodel',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Час проведення зустрічі (в хвилинах)'),
            preserve_default=False,
        ),
    ]
