# Generated by Django 5.0.7 on 2024-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_onlineclassesmodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclassregistrationmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='onlineclassregistrationmodel',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер (без +38)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclassregistrationmodel',
            name='user_name',
            field=models.CharField(default='name', max_length=50, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclassregistrationmodel',
            name='user_surname',
            field=models.CharField(default='surname', max_length=50, verbose_name='Прізвище'),
            preserve_default=False,
        ),
    ]
