# Generated by Django 5.0.7 on 2024-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_remove_onlineclassregistrationmodel_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineclassregistrationmodel',
            name='email',
            field=models.EmailField(default='post@example.com', max_length=254, verbose_name='Пошта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineclassregistrationmodel',
            name='email',
            field=models.EmailField(default='post@example.com', max_length=254, verbose_name='Пошта'),
            preserve_default=False,
        ),
    ]
