# Generated by Django 5.0.7 on 2024-07-17 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_offlineclassregistrationmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineclassesmodel',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
