# Generated by Django 5.0.7 on 2024-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_zoomtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomtoken',
            name='token_expires_str',
            field=models.DateTimeField(),
        ),
    ]
