# Generated by Django 5.0.7 on 2024-07-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_alter_zoomtoken_token_expires_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, verbose_name='Тег')),
            ],
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='video_name',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.CharField(default='Немає опису...', max_length=500, verbose_name='Опис відео'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='link',
            field=models.CharField(default='Посилання...', max_length=200, verbose_name='Посилання'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='name',
            field=models.CharField(default='Назва відео', max_length=50, verbose_name='Назва відео'),
        ),
        migrations.CreateModel(
            name='VideoCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, verbose_name='Коментар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.globalusermodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.videomodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
