# Generated by Django 5.0.7 on 2024-07-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_videotagmodel_remove_videomodel_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='tag',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.videotagmodel'),
            preserve_default=False,
        ),
    ]
