# Generated by Django 5.0.7 on 2024-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_videomodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='tag',
            field=models.ManyToManyField(blank=True, to='adminpanel.videotagmodel'),
        ),
    ]
