# Generated by Django 5.0.7 on 2024-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_remove_videomodel_tag_videomodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocommentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videocommentmodel',
            name='video',
        ),
        migrations.AddField(
            model_name='videocommentmodel',
            name='user',
            field=models.ManyToManyField(to='adminpanel.globalusermodel'),
        ),
        migrations.AddField(
            model_name='videocommentmodel',
            name='video',
            field=models.ManyToManyField(to='adminpanel.videomodel'),
        ),
    ]
