# Generated by Django 5.0.7 on 2024-07-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_remove_videocommentmodel_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCommentModel',
        ),
    ]
