# Generated by Django 5.0.7 on 2024-07-26 11:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_videocommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalusermodel',
            name='money_spent',
            field=models.IntegerField(verbose_name='Витрачено грошей'),
        ),
        migrations.AlterField(
            model_name='globalusermodel',
            name='subscription_end_date',
            field=models.DateField(verbose_name='Кінець підписки'),
        ),
        migrations.AlterField(
            model_name='globalusermodel',
            name='subscription_start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Початок підписки'),
        ),
        migrations.AlterField(
            model_name='globalusermodel',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.subscriptiontypemodel', verbose_name='Тип підписки'),
        ),
        migrations.AlterField(
            model_name='offlineclassesmodel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Опис:'),
        ),
        migrations.AlterField(
            model_name='onlineclassesmodel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Опис:'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Опис відео'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва відео'),
        ),
    ]
