# Generated by Django 5.0.7 on 2024-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_retreatdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name="Ім'я")),
                ('surname', models.TextField(max_length=50, verbose_name='Прізвище')),
                ('number', models.IntegerField(verbose_name='Номер (без +38)')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
            ],
        ),
        migrations.AlterField(
            model_name='retreatdescription',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Опис'),
        ),
    ]
