# Generated by Django 5.0.7 on 2024-07-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_retreatregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclassesmodel',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retreatregistration',
            name='number',
            field=models.IntegerField(verbose_name='Номер (без +380)'),
        ),
    ]
