# Generated by Django 5.0.7 on 2024-07-28 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_onlineclassesmodel_reminder_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineClassSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(verbose_name='Статус знижки')),
                ('coefficient', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Коефіцієнт (від 0 до 1)')),
                ('due_to', models.DateField(verbose_name='Кінець знижки')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClassSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(verbose_name='Статус знижки')),
                ('coefficient', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='Коефіцієнт (від 0 до 1)')),
                ('due_to', models.DateField(verbose_name='Кінець знижки')),
            ],
        ),
    ]
