# Generated by Django 5.0.7 on 2024-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_dayofopeneddoors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retreatdescription',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Увімкнено/Вимкнено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Опис відео'),
        ),
    ]
