# Generated by Django 5.0.7 on 2024-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_userphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone_number_field',
            field=models.IntegerField(default=0, verbose_name='Номер телефону'),
        ),
    ]
