# Generated by Django 5.0.7 on 2024-09-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_alter_userphonenumber_phone_number_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Посилання')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video', to='adminpanel.videomodel')),
            ],
        ),
    ]
